{{- if .Values.networkPolicy.enable }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "typesense.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "typesense.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "typesense.labels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    # Limit peering traffic only to the pods forming the cluster 
    - ports:
        - port: {{ .Values.peeringPort }}
      from:
        - podSelector:
            matchLabels:
              {{- include "typesense.labels" . | nindent 14 }}
    # Allow ingress traffic from anywhere to the app port (service)
    - ports:
        - port: {{ .Values.port }}
      from:
        - podSelector: {}
          namespaceSelector: {}
{{- end }}
