{{- if .Values.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "typesense.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "typesense.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["watch", "list"]
{{- end }}
