{{- if .Values.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-apikey" (include "typesense.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "typesense.labels" . | nindent 4 }}
data:
  TYPESENSE_API_KEY: {{ .Values.apiKey | b64enc }}
{{- end }}
