apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-headless" (include "typesense.fullname" .) }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "typesense.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "typesense.selectorLabels" . | nindent 4 }}
